# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Billy Prime
# email: billy.prime@billyprime.com
description: >- # this means to ignore newlines until "baseurl:"
  Photographer based in Washington, DC, USA.
baseurl: "https://billyprime.github.io/billyprime.com" # the subpath of your site, e.g. /blog
url: "https://billyprime.github.io" # the base hostname & protocol for your site, e.g. http://example.com
production_url : http://billyprime.github.io

static: "https://static.billyprime.com"
repository: billyprime/billyprime.com


author:
  name: "Billy Prime"
  email: "billy.prime@billyprime.com"
  twitter: billyprime
  github:  billyprime

paginate: 25
paginate_path: "/blog/:num/"

sass:
  sass_dir: assets
  load_paths:
    - assets/_sass
    - node_modules

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
#  - node_modules
  - update_boostrap.sh
  - yarn.lock
  - yarn-error.log
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - log

permalink: /blog/:categories/:title/

collections:
  category:
    output: true
  photos:
    output: true
  models:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: models
    values:
      layout: "model"
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"